version: '3.7'

networks:
  oraft:

x-node:
  &default-node
  build: .
  ports:
  - "7891"
  volumes:
  - ../..:/oraft

services:
  oraft-1:
    build:
      context: .
      dockerfile: ${DOCKER_CONF_DIR}/Dockerfile
    volumes:
    - ./${DOCKER_CONF_DIR}/oraft-1:/workspace
    ports:
    - 7891
    - '8181:8181'
    networks:
    - oraft
    container_name: oraft-1
    restart: always
  oraft-2:
    build:
      context: .
      dockerfile: ${DOCKER_CONF_DIR}/Dockerfile
    volumes:
    - ./${DOCKER_CONF_DIR}/oraft-2:/workspace
    ports:
    - 7891
    - '8182:8181'
    networks:
    - oraft
    container_name: oraft-2
    restart: always
  oraft-3:
    build:
      context: .
      dockerfile: ${DOCKER_CONF_DIR}/Dockerfile
    volumes:
    - ./${DOCKER_CONF_DIR}/oraft-3:/workspace
    ports:
    - 7891
    - '8183:8181'
    networks:
    - oraft
    container_name: oraft-3
    restart: always
  oraft-4:
    build:
      context: .
      dockerfile: ${DOCKER_CONF_DIR}/Dockerfile
    volumes:
    - ./${DOCKER_CONF_DIR}/oraft-4:/workspace
    ports:
    - 7891
    - '8184:8181'
    networks:
    - oraft
    container_name: oraft-4
  oraft-5:
    build:
      context: .
      dockerfile: ${DOCKER_CONF_DIR}/Dockerfile
    volumes:
    - ./${DOCKER_CONF_DIR}/oraft-5:/workspace
    ports:
    - 7891
    - '8185:8181'
    networks:
    - oraft
    container_name: oraft-5
    restart: always
  chaos-pause:
    image: gaiaadm/pumba
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    command: "--log-level info --random --interval 7s pause --duration 2s re2:oraft-*"
    depends_on:
    - oraft-1 
    - oraft-2 
    - oraft-3 
    - oraft-4 
    - oraft-5 
  chaos-delay:
    image: gaiaadm/pumba
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    command: "--log-level info --random --interval 11s netem --tc-image gaiadocker/iproute2 --duration 4s delay re2:oraft-*"
    depends_on:
    - oraft-1 
    - oraft-2 
    - oraft-3 
    - oraft-4 
    - oraft-5 
# chaos-loss:
#   image: gaiaadm/pumba
#   volumes:
#   - /var/run/docker.sock:/var/run/docker.sock
#   command: "--log-level info --random --interval 13s netem --tc-image gaiadocker/iproute2 --duration 3s loss re2:oraft-*"
#   depends_on:
#   - oraft-1 
#   - oraft-2 
#   - oraft-3 
#   - oraft-4 
#   - oraft-5 

