version: '3.7'

networks:
  oraft:

x-node: &default-node
  build:
    context: .
    dockerfile: ${DOCKER_CONF_DIR}/Dockerfile
  networks:
  - oraft
  restart: always

x-chaos-node: &chaos-node
  networks:
  - oraft
  restart: always

services:
  oraft-1:
    <<: *default-node
    volumes:
    - ./${DOCKER_CONF_DIR}/oraft-1:/workspace
    ports:
    - 7891
    - '8181:8181'
    container_name: oraft-1
  oraft-2:
    <<: *default-node
    volumes:
    - ./${DOCKER_CONF_DIR}/oraft-2:/workspace
    ports:
    - 7891
    - '8182:8181'
    container_name: oraft-2
  oraft-3:
    <<: *default-node
    volumes:
    - ./${DOCKER_CONF_DIR}/oraft-3:/workspace
    ports:
    - 7891
    - '8183:8181'
    container_name: oraft-3
  oraft-4:
    <<: *default-node
    volumes:
    - ./${DOCKER_CONF_DIR}/oraft-4:/workspace
    ports:
    - 7891
    - '8184:8181'
    container_name: oraft-4
  oraft-5:
    <<: *default-node
    volumes:
    - ./${DOCKER_CONF_DIR}/oraft-5:/workspace
    ports:
    - 7891
    - '8185:8181'
    container_name: oraft-5
  chaos-pause:
    <<: *chaos-node
    image: gaiaadm/pumba
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    command: "--log-level debug --random --interval 17s pause --duration 2s pause oraft-1 oraft-2 oraft-3 oraft-4 oraft-5"
    depends_on:
    - oraft-1
    - oraft-2
    - oraft-3
    - oraft-4
    - oraft-5
  chaos-delay:
    <<: *chaos-node
    image: gaiaadm/pumba
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    command: "--log-level debug --random --interval 23s netem --duration 3s delay oraft-1 oraft-2 oraft-3 oraft-4 oraft-5"
    depends_on:
    - oraft-1
    - oraft-2
    - oraft-3
    - oraft-4
    - oraft-5
  chaos-kill:
    <<: *chaos-node
    image: gaiaadm/pumba
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    command: "--log-level debug --random --interval 27s kill -l 1 -s SIGTERM oraft-1 oraft-2 oraft-3 oraft-4 oraft-5"
    depends_on:
    - oraft-1
    - oraft-2
    - oraft-3
    - oraft-4
    - oraft-5

