version: '3.7'

networks:
  oraft:

x-node:
  &default-node
  build: .
  ports:
  - "7891"
  volumes:
  - ../..:/oraft

services:
  oraft-1:
    build: .
    volumes:
    - ../..:/oraft
    - ./oraft-1:/workspace
    ports:
    - 7891
    - '8181:8181'
    networks:
    - oraft
    container_name: oraft-1
  oraft-2:
    build: .
    volumes:
    - ../..:/oraft
    - ./oraft-2:/workspace
    ports:
    - 7891
    - '8182:8181'
    networks:
    - oraft
    container_name: oraft-2
    depends_on:
    - oraft-1
  oraft-3:
    build: .
    volumes:
    - ../..:/oraft
    - ./oraft-3:/workspace
    ports:
    - 7891
    - '8183:8181'
    networks:
    - oraft
    container_name: oraft-3
    depends_on:
    - oraft-2
  oraft-4:
    build: .
    volumes:
    - ../..:/oraft
    - ./oraft-4:/workspace
    ports:
    - 7891
    - '8184:8181'
    networks:
    - oraft
    container_name: oraft-4
    depends_on:
    - oraft-3
  oraft-5:
    build: .
    volumes:
    - ../..:/oraft
    - ./oraft-5:/workspace
    ports:
    - 7891
    - '8185:8181'
    networks:
    - oraft
    container_name: oraft-5
    depends_on:
    - oraft-4
