version: '3.7'

networks:
  oraft:

x-node:
  &default-node
  build: .
  ports:
  - "7891"
  volumes:
  - ../..:/oraft

services:
  oraft-1:
    build:
      context: .
      dockerfile: example/docker/Dockerfile
    volumes:
    - ./example/docker/oraft-1:/workspace
    ports:
    - 7891
    - '8181:8181'
    networks:
    - oraft
    container_name: oraft-1
  oraft-2:
    build:
      context: .
      dockerfile: example/docker/Dockerfile
    volumes:
    - ./example/docker/oraft-2:/workspace
    ports:
    - 7891
    - '8182:8181'
    networks:
    - oraft
    container_name: oraft-2
  oraft-3:
    build:
      context: .
      dockerfile: example/docker/Dockerfile
    volumes:
    - ./example/docker/oraft-3:/workspace
    ports:
    - 7891
    - '8183:8181'
    networks:
    - oraft
    container_name: oraft-3
  oraft-4:
    build:
      context: .
      dockerfile: example/docker/Dockerfile
    volumes:
    - ./example/docker/oraft-4:/workspace
    ports:
    - 7891
    - '8184:8181'
    networks:
    - oraft
    container_name: oraft-4
  oraft-5:
    build:
      context: .
      dockerfile: example/docker/Dockerfile
    volumes:
    - ./example/docker/oraft-5:/workspace
    ports:
    - 7891
    - '8185:8181'
    networks:
    - oraft
    container_name: oraft-5
