name: CI

on:
 workflow_dispatch:
 pull_request:

jobs:
  build:
    runs-on: blacksmith-staging-4vcpu-ubuntu-2204
    strategy:
      fail-fast: false
      matrix:
        ocaml-compiler:
          - ocaml-base-compiler.4.14.1
          - ocaml-base-compiler.5.0.0
    steps:
      - uses: actions/checkout@v3
      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: useblacksmith/setup-ocaml@v1
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true
      - name: Install dependencies for testing
        run: opam install --deps-only --with-test .
      - name: Unit test
        run: opam exec -- dune runtest
      - name: Build Oraft
        run: opam exec -- dune build
      - uses: useblacksmith/setup-ruby@v2
        with:
          ruby-version: '3.1'
      - name: Install SQLite3 dev-tool
        run: sudo apt update && sudo apt install -y libsqlite3-dev
      - name: Smoke test
        run: opam exec -- smoke_test/run.sh
      - name: Archive the smoke test logs and status
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: smoke-test-logs-${{ matrix.ocaml-compiler }}
          path: example/oraft-*
      - name: Chaos test
        run: opam exec -- chaos_test/run.sh
      - name: Archive the chaos test logs and status
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: chaos-test-logs-${{ matrix.ocaml-compiler }}
          path: |
            chaos_test_*.log
            chaos_test/docker/oraft-*/oraft.log
            chaos_test/docker/oraft-*/state/log.jsonl

